### ISSUE TITLE
[invalid] 6490 Supported?

### ISSUE THREAD

**Issue by gelsas** [Freetz/freetz#50]
Is the 6490 (Vodafone branded) Box Supported?

**Comment by PeterPawn** [comment]
No, the original firmware (which will be modified by Freetz only) does not support the "kdg" branding.

**Comment by gelsas** [comment]
Is there another solution Like freetz for my Fritzbox 6490 with the kdg Branding ?

**Comment by PeterPawn** [comment]
Doubtless ... but:
- this isn't the right place for a discussion of anything other than a Freetz problem
- there are bulletin boards, where these questions are welcome - e.g. ip-phone-forum.de
- even in another place, you should consider to tell a recipient/reader much more 'bout your real goals - no-one here can realize, what your expectations are and why you want to modify the original firmware ... e.g. if you want to make the FRITZ!Box play music, it could be tricky due to the lack of a speaker
