### ISSUE TITLE
voipd never use openvpn tun0 (7490 Fritz!OS 6.84)

### ISSUE THREAD

**Issue by Greg57070** [Freetz/freetz#70]
Hello,

I'm trying to setup a SIP connexion from Fritzbox to my Asterisk SIP Server using an OpenVPN tunnel.

I'm facing a strange issue : The VPN is up, routing works well (from Fritzbox and clients behind fritzbox).

With a tcpdump, voipd is trying to connect to my server through internet connection (not using tunnel)
A traceroute from Fritzbox to my Asterisk show right path (using tun0).

Any idea why voipd don't use the tunnel ?

Thank you all for the good work, keep up with it !
Best regards,
Gregory

**Comment by feedzapper** [comment]
I'ts not a bug.
You need to set the right Interface in the "voip.cfg" for the number you are routing over the tunnel.
Change   sipiface = sipiface_tunnel;  in the  voip.cfg for the specific number.
Maybe you need also to do a "voipd -R" command after setting this to got registered.
Because the voipd daemon is started first on clean boot and the openvpn tunnel just AFTER the voipd daemon. The voipd daemon does not know from the openvpn tunnel...

**Comment by Greg57070** [comment]
Thanks a lot for your help !
It's working now !

Best regards,
Gregory
